<mxfile host="app.diagrams.net" modified="2026-09-27T00:00:00.000Z" agent="Codex" version="24.7.17" type="device">
  <diagram id="apps-tobe" name="Aplicaciones TO-BE">
    <mxGraphModel dx="1422" dy="794" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1400" pageHeight="900" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="title" value="TO-BE de Aplicaciones · Directorio de Extensiones" style="text;html=1;fontSize=24;fontStyle=1;fontColor=#123047;align=left;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="40" y="20" width="900" height="40" as="geometry"/></mxCell>
        <mxCell id="subtitle" value="Fuente única, conciliación por excepciones y aprovisionamiento con confirmación" style="text;html=1;fontSize=13;fontColor=#52606D;align=left;" vertex="1" parent="1"><mxGeometry x="40" y="58" width="900" height="30" as="geometry"/></mxCell>
        <mxCell id="m365" value="TENANT INSTITUCIONAL MICROSOFT 365" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;fontStyle=1;fontColor=#0F4C5C;fillColor=#F2F8FA;strokeColor=#0F6B78;strokeWidth=2;" vertex="1" parent="1"><mxGeometry x="230" y="105" width="900" height="680" as="geometry"/></mxCell>
        <mxCell id="dh" value="&lt;b&gt;Desarrollo Humano&lt;/b&gt;&lt;br&gt;Publica nómina autorizada" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#E9ECEF;strokeColor=#6C757D;fontColor=#263238;" vertex="1" parent="1"><mxGeometry x="25" y="185" width="170" height="70" as="geometry"/></mxCell>
        <mxCell id="prof" value="&lt;b&gt;Profesional de Experiencia y Servicio&lt;/b&gt;&lt;br&gt;Valida novedades y administra" style="ellipse;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;fontColor=#123047;" vertex="1" parent="1"><mxGeometry x="25" y="410" width="180" height="95" as="geometry"/></mxCell>
        <mxCell id="gest" value="&lt;b&gt;Gestoras de servicio ×4&lt;/b&gt;&lt;br&gt;Consultan vista vigente" style="ellipse;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;fontColor=#123047;" vertex="1" parent="1"><mxGeometry x="25" y="650" width="180" height="80" as="geometry"/></mxCell>
        <mxCell id="tec" value="&lt;b&gt;Analista de Tecnología&lt;/b&gt;&lt;br&gt;Atiende y confirma solicitud" style="ellipse;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;fontColor=#123047;" vertex="1" parent="1"><mxGeometry x="1185" y="475" width="180" height="85" as="geometry"/></mxCell>
        <mxCell id="pbx" value="&lt;b&gt;Plataforma PBX&lt;/b&gt;&lt;br&gt;Sistema externo · operación vigente" style="rounded=1;whiteSpace=wrap;html=1;double=1;fillColor=#E9ECEF;strokeColor=#6C757D;fontColor=#263238;" vertex="1" parent="1"><mxGeometry x="1185" y="650" width="180" height="80" as="geometry"/></mxCell>
        <mxCell id="lib" value="&lt;b&gt;Biblioteca de Nómina&lt;/b&gt;&lt;br&gt;SharePoint · acceso restringido&lt;br&gt;Archivo Excel de entrada" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="55" y="85" width="205" height="92" as="geometry"/></mxCell>
        <mxCell id="flowrec" value="&lt;b&gt;Flujo de Conciliación&lt;/b&gt;&lt;br&gt;Power Automate&lt;br&gt;Valida · compara · clasifica" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="345" y="85" width="210" height="92" as="geometry"/></mxCell>
        <mxCell id="dir" value="&lt;b&gt;Directorio Institucional&lt;/b&gt;&lt;br&gt;SharePoint List · fuente única&lt;br&gt;Id Empleado · estado · extensión" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="635" y="225" width="215" height="115" as="geometry"/></mxCell>
        <mxCell id="nov" value="&lt;b&gt;Lista de Novedades&lt;/b&gt;&lt;br&gt;Alta · baja · cambio · vacante&lt;br&gt;Resultado por excepción" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="345" y="245" width="210" height="105" as="geometry"/></mxCell>
        <mxCell id="sol" value="&lt;b&gt;Lista de Solicitudes&lt;/b&gt;&lt;br&gt;Estado · responsable · evidencia&lt;br&gt;Historial por transición" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="635" y="430" width="215" height="110" as="geometry"/></mxCell>
        <mxCell id="flowsol" value="&lt;b&gt;Flujo de Aprovisionamiento&lt;/b&gt;&lt;br&gt;Power Automate&lt;br&gt;Notifica · recuerda · confirma" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="345" y="440" width="210" height="92" as="geometry"/></mxCell>
        <mxCell id="teams" value="&lt;b&gt;Microsoft Teams&lt;/b&gt;&lt;br&gt;Interacción y notificaciones&lt;br&gt;No es el registro maestro" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6C8EBF;fontColor=#123047;" vertex="1" parent="m365"><mxGeometry x="55" y="445" width="205" height="92" as="geometry"/></mxCell>
        <mxCell id="view" value="&lt;b&gt;Vista de Consulta&lt;/b&gt;&lt;br&gt;SharePoint / Teams&lt;br&gt;Solo lectura para gestoras" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;fontColor=#173F2B;" vertex="1" parent="m365"><mxGeometry x="55" y="575" width="205" height="72" as="geometry"/></mxCell>
        <mxCell id="audit" value="&lt;b&gt;Versionado y Bitácora&lt;/b&gt;&lt;br&gt;Quién · qué · cuándo · resultado" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;fontColor=#5A4714;" vertex="1" parent="m365"><mxGeometry x="635" y="580" width="215" height="72" as="geometry"/></mxCell>
        <mxCell id="legend1" value="NUEVO / MEJORADO" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="960" y="20" width="170" height="30" as="geometry"/></mxCell>
        <mxCell id="legend2" value="EXTERNO" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#E9ECEF;strokeColor=#6C757D;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="1140" y="20" width="120" height="30" as="geometry"/></mxCell>
        <mxCell id="e1" value="archivo autorizado" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;endArrow=block;strokeColor=#52606D;" edge="1" parent="1" source="dh" target="lib"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e2" value="evento de carga" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="lib" target="flowrec"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e3" value="lee estado vigente" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="dir" target="flowrec"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e4" value="crea excepciones" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="flowrec" target="nov"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e5" value="valida / decide" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="1" source="prof" target="nov"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e6" value="actualiza dato" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="nov" target="dir"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7" value="si requiere PBX" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="nov" target="flowsol"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e8" value="registra solicitud" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="flowsol" target="sol"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e9" value="avisa" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C8EBF;" edge="1" parent="m365" source="flowsol" target="teams"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e10" value="notificación" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C8EBF;" edge="1" parent="1" source="teams" target="tec"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e11" value="actualiza estado y evidencia" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="1" source="tec" target="sol"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e12" value="procedimiento vigente" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C757D;dashed=1;" edge="1" parent="1" source="tec" target="pbx"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e13" value="confirmación" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="sol" target="dir"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e14" value="publica" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="m365" source="dir" target="view"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e15" value="consulta" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="1" source="view" target="gest"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e16" value="registra cambios" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#D6B656;dashed=1;" edge="1" parent="m365" source="dir" target="audit"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e17" value="registra transiciones" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#D6B656;dashed=1;" edge="1" parent="m365" source="sol" target="audit"><mxGeometry relative="1" as="geometry"/></mxCell>
      </root>
    </mxGraphModel>
  </diagram>
  <diagram id="process-tobe" name="Proceso TO-BE">
    <mxGraphModel dx="1422" dy="794" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="900" math="0" shadow="0">
      <root>
        <mxCell id="p0"/>
        <mxCell id="p1" parent="p0"/>
        <mxCell id="ptitle" value="Proceso TO-BE · Conciliación y aprovisionamiento" style="text;html=1;fontSize=24;fontStyle=1;fontColor=#123047;align=left;" vertex="1" parent="p1"><mxGeometry x="40" y="20" width="900" height="40" as="geometry"/></mxCell>
        <mxCell id="lane1" value="Desarrollo Humano" style="swimlane;html=1;horizontal=0;startSize=35;fillColor=#F4F5F7;strokeColor=#B0B7C3;fontStyle=1;" vertex="1" parent="p1"><mxGeometry x="40" y="90" width="1500" height="150" as="geometry"/></mxCell>
        <mxCell id="lane2" value="Power Automate / SharePoint" style="swimlane;html=1;horizontal=0;startSize=35;fillColor=#F2F8FA;strokeColor=#0F6B78;fontStyle=1;" vertex="1" parent="p1"><mxGeometry x="40" y="240" width="1500" height="180" as="geometry"/></mxCell>
        <mxCell id="lane3" value="Experiencia y Servicio" style="swimlane;html=1;horizontal=0;startSize=35;fillColor=#F4F8FC;strokeColor=#2B6F9C;fontStyle=1;" vertex="1" parent="p1"><mxGeometry x="40" y="420" width="1500" height="180" as="geometry"/></mxCell>
        <mxCell id="lane4" value="Dirección de Tecnología" style="swimlane;html=1;horizontal=0;startSize=35;fillColor=#F4F5F7;strokeColor=#6C757D;fontStyle=1;" vertex="1" parent="p1"><mxGeometry x="40" y="600" width="1500" height="170" as="geometry"/></mxCell>
        <mxCell id="start" value="Inicio del ciclo" style="ellipse;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;fontStyle=1;" vertex="1" parent="lane1"><mxGeometry x="80" y="52" width="120" height="48" as="geometry"/></mxCell>
        <mxCell id="upload" value="Publicar nómina en biblioteca restringida" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#6C757D;" vertex="1" parent="lane1"><mxGeometry x="250" y="42" width="190" height="68" as="geometry"/></mxCell>
        <mxCell id="validate" value="Validar estructura y llave Id Empleado" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane2"><mxGeometry x="475" y="55" width="190" height="68" as="geometry"/></mxCell>
        <mxCell id="validq" value="¿Archivo válido?" style="rhombus;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;" vertex="1" parent="lane2"><mxGeometry x="705" y="45" width="110" height="88" as="geometry"/></mxCell>
        <mxCell id="stop" value="Registrar error y notificar corrección" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8CECC;strokeColor=#B85450;" vertex="1" parent="lane2"><mxGeometry x="650" y="130" width="220" height="42" as="geometry"/></mxCell>
        <mxCell id="compare" value="Comparar nómina con directorio" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane2"><mxGeometry x="855" y="55" width="180" height="68" as="geometry"/></mxCell>
        <mxCell id="create" value="Crear novedades clasificadas" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane2"><mxGeometry x="1080" y="55" width="180" height="68" as="geometry"/></mxCell>
        <mxCell id="review" value="Validar excepciones" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;strokeWidth=2;" vertex="1" parent="lane3"><mxGeometry x="1080" y="55" width="180" height="68" as="geometry"/></mxCell>
        <mxCell id="pbxq" value="¿Requiere PBX?" style="rhombus;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;" vertex="1" parent="lane3"><mxGeometry x="875" y="45" width="125" height="88" as="geometry"/></mxCell>
        <mxCell id="updatedir" value="Actualizar directorio y publicar vista" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane3"><mxGeometry x="620" y="55" width="200" height="68" as="geometry"/></mxCell>
        <mxCell id="request" value="Registrar solicitud con estado y responsable" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane2"><mxGeometry x="400" y="55" width="210" height="68" as="geometry"/></mxCell>
        <mxCell id="operate" value="Aprovisionar o liberar extensión en PBX" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#6C757D;" vertex="1" parent="lane4"><mxGeometry x="400" y="50" width="220" height="68" as="geometry"/></mxCell>
        <mxCell id="confirm" value="Confirmar resultado y adjuntar evidencia" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;strokeWidth=2;" vertex="1" parent="lane4"><mxGeometry x="680" y="50" width="220" height="68" as="geometry"/></mxCell>
        <mxCell id="close" value="Actualizar estado, notificar gestoras y cerrar" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="lane2"><mxGeometry x="930" y="55" width="230" height="68" as="geometry"/></mxCell>
        <mxCell id="end" value="Directorio vigente" style="ellipse;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;fontStyle=1;" vertex="1" parent="lane3"><mxGeometry x="350" y="65" width="140" height="48" as="geometry"/></mxCell>
        <mxCell id="pe1" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="start" target="upload"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe2" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="upload" target="validate"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe3" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="validate" target="validq"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe4" value="No" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#B85450;" edge="1" parent="p1" source="validq" target="stop"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe5" value="Sí" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="validq" target="compare"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe6" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="compare" target="create"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe7" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="create" target="review"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe8" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="review" target="pbxq"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe9" value="No" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="pbxq" target="updatedir"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe10" value="Sí" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="pbxq" target="request"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe11" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="request" target="operate"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe12" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;" edge="1" parent="p1" source="operate" target="confirm"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe13" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="confirm" target="close"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe14" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="close" target="updatedir"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="pe15" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="p1" source="updatedir" target="end"><mxGeometry relative="1" as="geometry"/></mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
