<mxfile host="app.diagrams.net" modified="2026-09-27T00:00:00.000Z" agent="Codex" version="24.7.17" type="device">
  <diagram id="tech-tobe" name="Tecnología TO-BE">
    <mxGraphModel dx="1422" dy="794" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1500" pageHeight="900" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="title" value="TO-BE de Tecnología y Seguridad · Microsoft 365 institucional" style="text;html=1;fontSize=24;fontStyle=1;fontColor=#123047;align=left;" vertex="1" parent="1"><mxGeometry x="40" y="20" width="1000" height="42" as="geometry"/></mxCell>
        <mxCell id="subtitle" value="Despliegue lógico sin software externo ni integración inventada con la PBX" style="text;html=1;fontSize=13;fontColor=#52606D;align=left;" vertex="1" parent="1"><mxGeometry x="40" y="60" width="900" height="28" as="geometry"/></mxCell>
        <mxCell id="tenant" value="LÍMITE DE CONFIANZA · TENANT MICROSOFT 365" style="swimlane;html=1;rounded=1;startSize=34;fontStyle=1;fontColor=#0F4C5C;fillColor=#F2F8FA;strokeColor=#0F6B78;strokeWidth=2;" vertex="1" parent="1"><mxGeometry x="205" y="105" width="1060" height="685" as="geometry"/></mxCell>
        <mxCell id="idzone" value="IDENTIDAD Y ACCESO" style="swimlane;html=1;rounded=1;startSize=28;fontStyle=1;fillColor=#EDF4FB;strokeColor=#6C8EBF;" vertex="1" parent="tenant"><mxGeometry x="35" y="55" width="990" height="120" as="geometry"/></mxCell>
        <mxCell id="entraid" value="&lt;b&gt;Microsoft Entra ID&lt;/b&gt;&lt;br&gt;Identidad institucional y MFA" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6C8EBF;" vertex="1" parent="idzone"><mxGeometry x="30" y="40" width="215" height="60" as="geometry"/></mxCell>
        <mxCell id="readers" value="Grupo Consulta&lt;br&gt;solo lectura" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;" vertex="1" parent="idzone"><mxGeometry x="300" y="40" width="165" height="60" as="geometry"/></mxCell>
        <mxCell id="editors" value="Grupo Custodios&lt;br&gt;edición controlada" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;" vertex="1" parent="idzone"><mxGeometry x="505" y="40" width="165" height="60" as="geometry"/></mxCell>
        <mxCell id="techgroup" value="Grupo Tecnología&lt;br&gt;gestión de solicitudes" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;" vertex="1" parent="idzone"><mxGeometry x="710" y="40" width="190" height="60" as="geometry"/></mxCell>
        <mxCell id="datazone" value="DATOS INSTITUCIONALES · SHAREPOINT ONLINE" style="swimlane;html=1;rounded=1;startSize=28;fontStyle=1;fillColor=#F3FBF6;strokeColor=#288A55;" vertex="1" parent="tenant"><mxGeometry x="35" y="205" width="620" height="260" as="geometry"/></mxCell>
        <mxCell id="paylib" value="Biblioteca Nómina&lt;br&gt;acceso restringido" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#FFFFFF;strokeColor=#288A55;" vertex="1" parent="datazone"><mxGeometry x="30" y="55" width="160" height="75" as="geometry"/></mxCell>
        <mxCell id="dirlist" value="Lista Directorio&lt;br&gt;fuente única" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="datazone"><mxGeometry x="230" y="55" width="160" height="75" as="geometry"/></mxCell>
        <mxCell id="novlist" value="Lista Novedades&lt;br&gt;excepciones" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="datazone"><mxGeometry x="430" y="55" width="150" height="75" as="geometry"/></mxCell>
        <mxCell id="reqlist" value="Lista Solicitudes&lt;br&gt;estados y evidencia" style="shape=cylinder3;whiteSpace=wrap;html=1;boundedLbl=1;backgroundOutline=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="datazone"><mxGeometry x="130" y="155" width="165" height="75" as="geometry"/></mxCell>
        <mxCell id="audit" value="Versionado y bitácora&lt;br&gt;por elemento" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;" vertex="1" parent="datazone"><mxGeometry x="350" y="155" width="175" height="65" as="geometry"/></mxCell>
        <mxCell id="autozone" value="AUTOMATIZACIÓN · POWER AUTOMATE" style="swimlane;html=1;rounded=1;startSize=28;fontStyle=1;fillColor=#F3FBF6;strokeColor=#288A55;" vertex="1" parent="tenant"><mxGeometry x="685" y="205" width="340" height="260" as="geometry"/></mxCell>
        <mxCell id="flow1" value="Flujo de conciliación&lt;br&gt;validar · comparar · clasificar" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="autozone"><mxGeometry x="35" y="55" width="270" height="65" as="geometry"/></mxCell>
        <mxCell id="flow2" value="Flujo de aprovisionamiento&lt;br&gt;notificar · recordar · cerrar" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DDF4E7;strokeColor=#288A55;strokeWidth=2;" vertex="1" parent="autozone"><mxGeometry x="35" y="140" width="270" height="65" as="geometry"/></mxCell>
        <mxCell id="svc" value="Conexión institucional&lt;br&gt;privilegio mínimo · copropiedad" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;" vertex="1" parent="autozone"><mxGeometry x="35" y="215" width="270" height="35" as="geometry"/></mxCell>
        <mxCell id="uxzone" value="EXPERIENCIA Y NOTIFICACIÓN" style="swimlane;html=1;rounded=1;startSize=28;fontStyle=1;fillColor=#EDF4FB;strokeColor=#6C8EBF;" vertex="1" parent="tenant"><mxGeometry x="35" y="495" width="990" height="155" as="geometry"/></mxCell>
        <mxCell id="teams" value="Microsoft Teams&lt;br&gt;notificaciones y acceso a listas" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6C8EBF;" vertex="1" parent="uxzone"><mxGeometry x="60" y="50" width="230" height="65" as="geometry"/></mxCell>
        <mxCell id="browser" value="Navegador / cliente M365&lt;br&gt;vistas según rol" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6C8EBF;" vertex="1" parent="uxzone"><mxGeometry x="380" y="50" width="230" height="65" as="geometry"/></mxCell>
        <mxCell id="excel" value="Microsoft Excel&lt;br&gt;entrada / exportación controlada" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6C8EBF;" vertex="1" parent="uxzone"><mxGeometry x="700" y="50" width="230" height="65" as="geometry"/></mxCell>
        <mxCell id="hr" value="Sistema de Desarrollo Humano&lt;br&gt;externo · origina nómina" style="rounded=1;whiteSpace=wrap;html=1;double=1;fillColor=#E9ECEF;strokeColor=#6C757D;" vertex="1" parent="1"><mxGeometry x="20" y="235" width="160" height="75" as="geometry"/></mxCell>
        <mxCell id="pbx" value="Plataforma PBX&lt;br&gt;externa · operación de Tecnología" style="rounded=1;whiteSpace=wrap;html=1;double=1;fillColor=#E9ECEF;strokeColor=#6C757D;" vertex="1" parent="1"><mxGeometry x="1305" y="555" width="170" height="80" as="geometry"/></mxCell>
        <mxCell id="users" value="Usuarios institucionales&lt;br&gt;gestoras · profesional · Tecnología" style="ellipse;whiteSpace=wrap;html=1;fillColor=#D9EAF7;strokeColor=#2B6F9C;" vertex="1" parent="1"><mxGeometry x="25" y="580" width="165" height="85" as="geometry"/></mxCell>
        <mxCell id="controls" value="&lt;b&gt;Controles transversales&lt;/b&gt;&lt;br&gt;• Menor privilegio&lt;br&gt;• Validación e Id Empleado&lt;br&gt;• Versionado y trazabilidad&lt;br&gt;• Compartición restringida&lt;br&gt;• Recuperación controlada" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;align=left;spacingLeft=12;" vertex="1" parent="1"><mxGeometry x="1300" y="155" width="180" height="180" as="geometry"/></mxCell>
        <mxCell id="e1" value="exporta archivo" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C757D;" edge="1" parent="1" source="hr" target="paylib"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e2" value="autentica" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="1" source="users" target="entraid"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e3" value="autoriza" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="tenant" source="entraid" target="readers"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="tenant" source="entraid" target="editors"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e5" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#2B6F9C;" edge="1" parent="tenant" source="entraid" target="techgroup"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e6" value="lee / escribe" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="tenant" source="flow1" target="dirlist"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7" value="crea" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="tenant" source="flow1" target="novlist"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e8" value="lee" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="tenant" source="paylib" target="flow1"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e9" value="actualiza" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#288A55;" edge="1" parent="tenant" source="flow2" target="reqlist"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e10" value="notifica" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C8EBF;" edge="1" parent="tenant" source="flow2" target="teams"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e11" value="consulta" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C8EBF;" edge="1" parent="tenant" source="browser" target="dirlist"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e12" value="entrada / salida" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C8EBF;" edge="1" parent="tenant" source="excel" target="paylib"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e13" value="registra" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#D6B656;dashed=1;" edge="1" parent="tenant" source="dirlist" target="audit"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e14" value="registra" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#D6B656;dashed=1;" edge="1" parent="tenant" source="reqlist" target="audit"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e15" value="operación manual vigente" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;strokeColor=#6C757D;dashed=1;" edge="1" parent="1" source="teams" target="pbx"><mxGeometry relative="1" as="geometry"/></mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
